const textdark = "#000";
const textlight = "#fff";

let projects = {
 
    Tine: {
        name: "Tine",
        url: "tine",
        frontpage: true,
        shorttitle: "Lorem ipsum dette er en veldig kort tekst som er et avsnitt ca.",
        thumbimg: "Smartplanlegger-mockups2.png",
        color: "#306AAD",
        textcolor: textlight,
    },
    Imdi: {
        name: "Imdi",
        url: "imdi",
        frontpage: true,
        shorttitle: "Lorem ipsum dette er en veldig kort tekst som er et avsnitt ca.",
        thumbimg: "imdi_toppbilde.jpg",
        color: "#59BBC3",
        textcolor: textlight,
    },
    Nordea: {
        name: "Nordea",
        url: "nordea",
        frontpage: true,
        shorttitle: "Nordea News",
        thumbimg: "Nordea_forsidebilde.jpg",
        color: "#1C26A5",
        textcolor: textlight,
    },
    Bouvetgrandprix: {
        name: "Bouvet Grand Prix",
        url: "bouvetgrandprix",
        frontpage: true,
        shorttitle: "Bouvet Grand Prix",
        thumbimg: "bouvet-grandprix-mobil.png",
        color: "#2B2E35",
        textcolor: textlight,
    },
    OBOS: {
        name: "OBOS",
        url: "obos",
        frontpage: true,
        shorttitle: "Forkjøpsrett",
        thumbimg: "Obos-mockup-thumb.jpg",
        color: "#77C69E",
        textcolor: textlight,
    },
    Fjordland: {
        name: "Fjordland",
        url: "fjordland",
        frontpage: true,
        shorttitle: "Web",
        thumbimg: "Fjordland-mockups-thumb.jpg",
        color: "#AE697A",
        textcolor: textlight,
    },
    SNLA: {
        name: "SNLA",
        url: "snla",
        frontpage: true,
        shorttitle: "Appen som kan redde liv",
        thumbimg: "snla_thumb_love.png",
        color: "#3A5862",
        textcolor: textlight,
    },
    Flytoget: {
        name: "Flytoget",
        url: "flytoget",
        frontpage: true,
        shorttitle: "Kampanjer",
        thumbimg: "flytoget.jpg",
        color: "#304262",
        textcolor: textlight,
    },
    Bouvetfilmen: {
        name: "Bouvet",
        url: "bouvetfilmen",
        frontpage: true,
        shorttitle: "Bouvet profilfilm",
        thumbimg: "bouvetfilmen-thumb.jpg",
        color: "#F2A04E",
        textcolor: textlight,
    },
    Norwegian: {
        name: "Norwegian",
        url: "norwegian",
        frontpage: true,
        shorttitle: "Kampanjer",
        thumbimg: "Norwegian.jpg",
        color: "#C2584C",
        textcolor: textlight,
    },
    StatensVegvesen: {
        name: "Statens Vegvesen",
        url: "statensvegvesen",
        frontpage: true,
        shorttitle: "Fast & safe",
        thumbimg: "Fast&safe2.jpg",
        color: "#1F1E22",
        textcolor: textlight,
    },
    Ruter: {
        name: "Ruter",
        url: "ruter",
        frontpage: true,
        shorttitle: "Kampanjer",
        thumbimg: "Ruter2.jpg",
        color: "#E67947",
        textcolor: textlight,
    },
    BlockWatne: {
        name: "Block Watne",
        url: "blockwatne",
        frontpage: true,
        shorttitle: "Flytt ut av byen",
        thumbimg: "flyttutavbyen.jpg",
        color: "#B1A991",
        textcolor: textlight,
    },
    Millum: {
        name: "Millum",
        url: "millum",
        frontpage: true,
        shorttitle: "Filmer om Millum",
        thumbimg: "Millum_forsidebilde_medium.jpg",
        color: "#DF754C",
        textcolor: textlight,
    },
    Sparebank1: {
        name: "Sparebank 1",
        url: "sparebank1",
        frontpage: true,
        shorttitle: "Film & aktiviteter",
        thumbimg: "Sparebank1.jpg",
        color: "#65B3E3",
        textcolor: textlight,
    },
    Kreftforeningen: {
        name: "Kreftforeningen",
        url: "kreftforeningen",
        frontpage: false,
        shorttitle: "Stjerner gir håp",
        thumbimg: "Kreftforeningen.jpg",
        color: "#2B2E35",
        textcolor: textlight,
    },
    Student: {
        name: "Studentarbeider",
        url: "studentarbeider",
        frontpage: false,
        shorttitle: "Diverse",
        thumbimg: "Ikea_stolleken_forsidebilde_small.jpg",
        color: "#2B2E35",
        textcolor: textlight,
    },
    Photoshoping: {
        name: "Photoshoping",
        url: "photoshoping",
        frontpage: true,
        shorttitle: "Ekstra",
        thumbimg: "Nike_Halloween_newedition_retusj_8.jpg",
        color: "#C6B3AA",
        textcolor: textlight,
    },
};
  
  
